### ISSUE TITLE
(Unrelated) About freeage

### ISSUE THREAD

**Issue by gregstein** [puzzlepaint/camera_calibration#13]
Hello friend, How are you doing ?

Many users are interested to use Freeage. I posted a [youtube video](https://www.youtube.com/watch?v=tUvhNNZOYKE) about it and people seem to love it.

It would be great if you restore it back and ignore whatever copyright none-sense they talk you out in that issue 24. They are obviously so mad that you managed to pull an easy to use app interface while they are violating game asset usage themselves. 

I'm sure that as long as Freeage remains free of charge (not a paid service) It'll be like WK and [AoE2Tools](https://github.com/gregstein/AoE2Tools). I myself have a few hardcoded files into my project AoE2Tools. Same thing goes for WK. 

Microsoft owns Github and still none of us got banned why? Because we are promoting their product and forcing people to buy aoe2. Did you know that MS sponsored many WK tournaments in the past casted by memb and T90?? 

Trust me! When it comes to marketing and as long as you're helping them grow the business. All you'll be getting is support. MS have had well qualified marketing workers and they are not stupid to shut down anyone of us because that'll just bad marketing.

Come on we are waiting for that project to be restored <3 Thank you

Have a nice day,

**Comment by puzzlepaint** [comment]
Hi, thanks for your message and for making the video. Maybe I'll return to the FreeAge project at a later time when the conditions seem better, but right now I unfortunately don't think that it's a good idea, I am sorry. There is currently still an older fork of the project accessible at https://github.com/grst/freeage for anyone who is still interested in the code. Have a nice day as well.
