### ISSUE TITLE
Support for CUDA 11

### ISSUE THREAD

**Issue by invenibo** [puzzlepaint/camera_calibration#32]
When trying to compile under Ubuntu 20.04 with CUDA 11.2 installed, the compiler fails with the following output:

> /usr/local/cuda/targets/x86_64-linux/include/thrust/system/cuda/config.h:78:2: error: #error The version of CUB in your include path is not compatible with this release of Thrust. CUB is now included in the CUDA Toolkit, so you no longer need to use your own checkout of CUB. Define THRUST_IGNORE_CUB_VERSION_CHECK to ignore this.
   78 | #error The version of CUB in your include path is not compatible with this release of Thrust. CUB is now included in the CUDA Toolkit, so you no longer need to use your own checkout of CUB. Define THRUST_IGNORE_CUB_VERSION_CHECK to ignore this.

This version mismatch is due to the fact that CUB(1.8.0) is included in the project as a third party library. However, starting from Version 11, CUDA already includes the correct version of CUB.

This problem can be solved by simply removing `third_party/cub-1.8.0` from the `target_include_directories` for the target `camera_calibration_baselib`. To make it backward compatible a condition could be used e.g. ( `if(CUDA_VERSION_MAJOR VERSION_LESS 11`).

Furthermore, Thrust is complaining about the C++ standard: 
> usr/local/cuda/targets/x86_64-linux/include/thrust/detail/config/cpp_dialect.h:118:13: warning: Thrust requires C++14. Please pass -std=c++14 to your compiler. Define THRUST_IGNORE_DEPRECATED_CPP_DIALECT to suppress this message.
  118 |   THRUST_COMPILER_DEPRECATION(C++14, pass -std=c++14 to your compiler);

Perhaps it would be worth considering to bump the standard up to 14.

**Comment by puzzlepaint** [comment]
Thanks for reporting! I implemented the changes as suggested (it was necessary to use `CMAKE_CUDA_COMPILER_VERSION` instead of `CUDA_VERSION_MAJOR`).
