### ISSUE TITLE
How to implement binocular stereo distance measurement

### ISSUE THREAD

**Issue by StarryPath** [puzzlepaint/camera_calibration#52]
Hi @puzzlepaint 
I have a binocular camera composed of two cameras with fixed relative positions. I can complete the feature point matching of two pictures. I use the central generic model to calibrate two cameras respectively. How can I calculate the spatial position of feature points?

**Comment by puzzlepaint** [comment]
You might want to have a look at feature point triangulation algorithms.

However, I think that this question is offtopic here, as this is not a general Computer Vision support forum but an issue tracker for my camera calibration program, so I will close this issue here.
