### ISSUE TITLE
Convergence issue

### ISSUE THREAD

**Issue by boazsaips** [puzzlepaint/camera_calibration#65]
Hi,

I'm trying to calibrate a central-generic model to my iPhone camera (as a test). I took ~400 photos of the calibration board, with a good coverage of almost all pixels, but the error histogram I get at the end of the calibration process does not look good:

![report_camera0_errors_histogram](https://user-images.githubusercontent.com/111227848/192699510-35a0ba83-d1de-4b08-93c1-0a80c2342faa.png)

The image resolution is 4032x3024 and the I set the CELL_SIZE to 30. I tried CELL_SIZE=80 but the histogram remained quite similar.
Am I missing something? your advice will be appreciated.

Boaz

**Comment by puzzlepaint** [comment]
Hi, some things to check could be:
* Is any issue visible in the other visualizations of the calibration result?
* What is the clarity of the pictures when zooming in to the pattern features? In case the centers of the star features aren't sharp, a larger spread of the reprojection errors, as in your result, would be expected.
* If the camera uses a rolling shutter, and you took the pictures with the iPhone held in your hand, how much does it affect the result? I imagine that pressing the button to take a picture leads to some small shaking of the device, and the rotational part of that might cause relevant distortions for rolling-shutter cameras.

**Comment by boazsaips** [comment]
Apparently, the problem was the autofocus mechanism of the iPhone camera. I took ~50 pictures again, with the autofocus disabled, and the optimization converged nicely.
